### ISSUE TITLE
Suggestion: Whisper and Permissions

### ISSUE THREAD

**Issue by bearsy1** [ctbritt/gpt4-dnd5e#1]
First off, thank you for making this tool for the community!

I think it would be a good idea to add an option in the settings to toggle the results to be whispered to chat. Or perhaps have the queries whispered by default, and DMs can opt to have them shown publicly with a setting? Either way, it would be great to have that option.

Another thing that, admittedly I haven't had the chance to test as a player, but I'm also worried about players being able to use this module '?rule/stat/item/etc.' and potentially abusing the owner's api key. Is it set to only be usable by those with DM/GM permissions by default? If not, could we get those settings as options?

Please and once again, thank you!

**Comment by ctbritt** [comment]
These are great ideas, thank you. I'll see what I can do with it.
